### ISSUE TITLE
Sinilink XY-WFUSB

### ISSUE THREAD

**Issue by nicholaswilde** [nicholaswilde/notes#10]
### USB TTL Board

```
( )          <- 
( )          <- 
( )          <- RX
( )          <- TX
( )          <- 
( )          <-
```

### XY-WFUSB

```
usb female port
push button is on the other side of the board 
( )          <- 3v3
( )          <- rst
( )          <- gpio0
( )          <- rx
( )          <- tx
( )          <- gnd
usb male port
```

- Connect own power for device 
- Connect USB TTL adapter first 
- Use esphome command line to flash

```shell
esphome wizard switch.yaml
esphome run switch.yaml
```

###  switch.yaml

Configure reset pin if it doesn't work.

```yaml
...
uart:
  id: uart_bus
  tx_pin: GPIO1
  rx_pin: GPIO3
  rts_pin: GPIO14
  cts_pin: GPIO15
  baud_rate: 115200
```

- https://rudd-o.com/linux-and-free-software/switching-an-usb-load-on-or-off-using-the-sinilink-xy-wfusb-and-esphome
- https://tech.scargill.net/aliexpress-sinilink-wifi-usb-controller/
- https://community.home-assistant.io/t/sinilink-wifi-usb-controller-xy-wfusb-turns-usb-port-power-on-off-esphome-yaml/574532/2
- https://esphome.io/guides/getting_started_command_line.html
